### ISSUE TITLE
Links to docs in README are broken

### ISSUE THREAD

**Issue by tlnagy** [queryverse/Query.jl#184]
The links to the documentation in the README are returning a 404.

**Comment by andyferris** [comment]
Yes - anyone know where I can find them?

**Comment by davidanthoff** [comment]
I believe they should work now again? http://www.queryverse.org/Query.jl/stable/

**Comment by mcarpe** [comment]
The link on the README is http://www.david-anthoff.com/Query.jl/stable/ and that's still broken. The one above works, though
